from __future__ import annotations

import platform
import sys
from pathlib import Path

from inline_snapshot import snapshot


def test_pyinstaller_datas():
    from kimi_cli.utils.pyinstaller import datas

    project_root = Path(__file__).parent.parent.parent
    python_version = f"{sys.version_info.major}.{sys.version_info.minor}"
    site_packages = f".venv/lib/python{python_version}/site-packages"
    rg_binary = "rg.exe" if platform.system() == "Windows" else "rg"
    has_rg_binary = (project_root / "src/kimi_cli/deps/bin" / rg_binary).exists()
    datas = [
        (
            Path(path)
            .relative_to(project_root)
            .as_posix()
            .replace(".venv/Lib/site-packages", site_packages),
            Path(dst).as_posix(),
        )
        for path, dst in datas
    ]

    datas = [(p, d) for p, d in datas if "web/static" not in d]

    expected_datas = [
        (
            f"{site_packages}/dateparser/data/dateparser_tz_cache.pkl",
            "dateparser/data",
        ),
        (
            f"{site_packages}/fastmcp/../fastmcp-2.12.5.dist-info/INSTALLER",
            "fastmcp/../fastmcp-2.12.5.dist-info",
        ),
        (
            f"{site_packages}/fastmcp/../fastmcp-2.12.5.dist-info/METADATA",
            "fastmcp/../fastmcp-2.12.5.dist-info",
        ),
        (
            f"{site_packages}/fastmcp/../fastmcp-2.12.5.dist-info/RECORD",
            "fastmcp/../fastmcp-2.12.5.dist-info",
        ),
        (
            f"{site_packages}/fastmcp/../fastmcp-2.12.5.dist-info/REQUESTED",
            "fastmcp/../fastmcp-2.12.5.dist-info",
        ),
        (
            f"{site_packages}/fastmcp/../fastmcp-2.12.5.dist-info/WHEEL",
            "fastmcp/../fastmcp-2.12.5.dist-info",
        ),
        (
            f"{site_packages}/fastmcp/../fastmcp-2.12.5.dist-info/entry_points.txt",
            "fastmcp/../fastmcp-2.12.5.dist-info",
        ),
        (
            f"{site_packages}/fastmcp/../fastmcp-2.12.5.dist-info/licenses/LICENSE",
            "fastmcp/../fastmcp-2.12.5.dist-info/licenses",
        ),
        (
            "src/kimi_cli/CHANGELOG.md",
            "kimi_cli",
        ),
        ("src/kimi_cli/agents/default/agent.yaml", "kimi_cli/agents/default"),
        ("src/kimi_cli/agents/default/sub.yaml", "kimi_cli/agents/default"),
        ("src/kimi_cli/agents/default/system.md", "kimi_cli/agents/default"),
        ("src/kimi_cli/agents/okabe/agent.yaml", "kimi_cli/agents/okabe"),
        ("src/kimi_cli/prompts/compact.md", "kimi_cli/prompts"),
        ("src/kimi_cli/prompts/init.md", "kimi_cli/prompts"),
        (
            "src/kimi_cli/skills/kimi-cli-help/SKILL.md",
            "kimi_cli/skills/kimi-cli-help",
        ),
        (
            "src/kimi_cli/skills/skill-creator/SKILL.md",
            "kimi_cli/skills/skill-creator",
        ),
        ("src/kimi_cli/tools/ask_user/description.md", "kimi_cli/tools/ask_user"),
        (
            "src/kimi_cli/tools/dmail/dmail.md",
            "kimi_cli/tools/dmail",
        ),
        (
            "src/kimi_cli/tools/file/glob.md",
            "kimi_cli/tools/file",
        ),
        (
            "src/kimi_cli/tools/file/grep.md",
            "kimi_cli/tools/file",
        ),
        (
            "src/kimi_cli/tools/file/read.md",
            "kimi_cli/tools/file",
        ),
        (
            "src/kimi_cli/tools/file/read_media.md",
            "kimi_cli/tools/file",
        ),
        (
            "src/kimi_cli/tools/file/replace.md",
            "kimi_cli/tools/file",
        ),
        (
            "src/kimi_cli/tools/file/write.md",
            "kimi_cli/tools/file",
        ),
        ("src/kimi_cli/tools/multiagent/create.md", "kimi_cli/tools/multiagent"),
        ("src/kimi_cli/tools/multiagent/task.md", "kimi_cli/tools/multiagent"),
        ("src/kimi_cli/tools/shell/bash.md", "kimi_cli/tools/shell"),
        ("src/kimi_cli/tools/shell/powershell.md", "kimi_cli/tools/shell"),
        (
            "src/kimi_cli/tools/think/think.md",
            "kimi_cli/tools/think",
        ),
        (
            "src/kimi_cli/tools/todo/set_todo_list.md",
            "kimi_cli/tools/todo",
        ),
        (
            "src/kimi_cli/tools/web/fetch.md",
            "kimi_cli/tools/web",
        ),
        (
            "src/kimi_cli/tools/web/search.md",
            "kimi_cli/tools/web",
        ),
    ]
    if has_rg_binary:
        expected_datas.append((f"src/kimi_cli/deps/bin/{rg_binary}", "kimi_cli/deps/bin"))

    assert sorted(datas) == snapshot([
    (
        ".venv/lib/python3.14/site-packages/dateparser/data/dateparser_tz_cache.pkl",
        "dateparser/data",
    ),
    (
        ".venv/lib/python3.14/site-packages/fastmcp/../fastmcp-2.12.5.dist-info/INSTALLER",
        "fastmcp/../fastmcp-2.12.5.dist-info",
    ),
    (
        ".venv/lib/python3.14/site-packages/fastmcp/../fastmcp-2.12.5.dist-info/METADATA",
        "fastmcp/../fastmcp-2.12.5.dist-info",
    ),
    (
        ".venv/lib/python3.14/site-packages/fastmcp/../fastmcp-2.12.5.dist-info/RECORD",
        "fastmcp/../fastmcp-2.12.5.dist-info",
    ),
    (
        ".venv/lib/python3.14/site-packages/fastmcp/../fastmcp-2.12.5.dist-info/REQUESTED",
        "fastmcp/../fastmcp-2.12.5.dist-info",
    ),
    (
        ".venv/lib/python3.14/site-packages/fastmcp/../fastmcp-2.12.5.dist-info/WHEEL",
        "fastmcp/../fastmcp-2.12.5.dist-info",
    ),
    (
        ".venv/lib/python3.14/site-packages/fastmcp/../fastmcp-2.12.5.dist-info/entry_points.txt",
        "fastmcp/../fastmcp-2.12.5.dist-info",
    ),
    (
        ".venv/lib/python3.14/site-packages/fastmcp/../fastmcp-2.12.5.dist-info/licenses/LICENSE",
        "fastmcp/../fastmcp-2.12.5.dist-info/licenses",
    ),
    ("src/kimi_cli/CHANGELOG.md", "kimi_cli"),
    ("src/kimi_cli/agents/default/agent.yaml", "kimi_cli/agents/default"),
    ("src/kimi_cli/agents/default/sub.yaml", "kimi_cli/agents/default"),
    ("src/kimi_cli/agents/default/system.md", "kimi_cli/agents/default"),
    ("src/kimi_cli/agents/okabe/agent.yaml", "kimi_cli/agents/okabe"),
    ("src/kimi_cli/deps/bin/rg", "kimi_cli/deps/bin"),
    ("src/kimi_cli/prompts/compact.md", "kimi_cli/prompts"),
    ("src/kimi_cli/prompts/init.md", "kimi_cli/prompts"),
    (
        "src/kimi_cli/skills/academic-researcher/SKILL.md",
        "kimi_cli/skills/academic-researcher",
    ),
    (
        "src/kimi_cli/skills/algorithmic-art/LICENSE.txt",
        "kimi_cli/skills/algorithmic-art",
    ),
    ("src/kimi_cli/skills/algorithmic-art/SKILL.md", "kimi_cli/skills/algorithmic-art"),
    (
        "src/kimi_cli/skills/algorithmic-art/templates/generator_template.js",
        "kimi_cli/skills/algorithmic-art/templates",
    ),
    (
        "src/kimi_cli/skills/algorithmic-art/templates/viewer.html",
        "kimi_cli/skills/algorithmic-art/templates",
    ),
    (
        "src/kimi_cli/skills/artifacts-builder/LICENSE.txt",
        "kimi_cli/skills/artifacts-builder",
    ),
    (
        "src/kimi_cli/skills/artifacts-builder/SKILL.md",
        "kimi_cli/skills/artifacts-builder",
    ),
    (
        "src/kimi_cli/skills/artifacts-builder/scripts/bundle-artifact.sh",
        "kimi_cli/skills/artifacts-builder/scripts",
    ),
    (
        "src/kimi_cli/skills/artifacts-builder/scripts/init-artifact.sh",
        "kimi_cli/skills/artifacts-builder/scripts",
    ),
    (
        "src/kimi_cli/skills/artifacts-builder/scripts/shadcn-components.tar.gz",
        "kimi_cli/skills/artifacts-builder/scripts",
    ),
    (
        "src/kimi_cli/skills/brand-guidelines/LICENSE.txt",
        "kimi_cli/skills/brand-guidelines",
    ),
    (
        "src/kimi_cli/skills/brand-guidelines/SKILL.md",
        "kimi_cli/skills/brand-guidelines",
    ),
    ("src/kimi_cli/skills/canvas-design/LICENSE.txt", "kimi_cli/skills/canvas-design"),
    ("src/kimi_cli/skills/canvas-design/SKILL.md", "kimi_cli/skills/canvas-design"),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/ArsenalSC-OFL.txt",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/ArsenalSC-Regular.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/BigShoulders-Bold.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/BigShoulders-OFL.txt",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/BigShoulders-Regular.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/Boldonse-OFL.txt",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/Boldonse-Regular.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/BricolageGrotesque-Bold.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/BricolageGrotesque-OFL.txt",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/BricolageGrotesque-Regular.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/CrimsonPro-Bold.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/CrimsonPro-Italic.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/CrimsonPro-OFL.txt",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/CrimsonPro-Regular.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/DMMono-OFL.txt",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/DMMono-Regular.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/EricaOne-OFL.txt",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/EricaOne-Regular.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/GeistMono-Bold.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/GeistMono-OFL.txt",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/GeistMono-Regular.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/Gloock-OFL.txt",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/Gloock-Regular.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/IBMPlexMono-Bold.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/IBMPlexMono-OFL.txt",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/IBMPlexMono-Regular.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/IBMPlexSerif-Bold.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/IBMPlexSerif-BoldItalic.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/IBMPlexSerif-Italic.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/IBMPlexSerif-Regular.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/InstrumentSans-Bold.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/InstrumentSans-BoldItalic.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/InstrumentSans-Italic.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/InstrumentSans-OFL.txt",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/InstrumentSans-Regular.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/InstrumentSerif-Italic.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/InstrumentSerif-Regular.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/Italiana-OFL.txt",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/Italiana-Regular.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/JetBrainsMono-Bold.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/JetBrainsMono-OFL.txt",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/JetBrainsMono-Regular.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/Jura-Light.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/Jura-Medium.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/Jura-OFL.txt",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/LibreBaskerville-OFL.txt",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/LibreBaskerville-Regular.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/Lora-Bold.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/Lora-BoldItalic.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/Lora-Italic.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/Lora-OFL.txt",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/Lora-Regular.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/NationalPark-Bold.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/NationalPark-OFL.txt",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/NationalPark-Regular.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/NothingYouCouldDo-OFL.txt",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/NothingYouCouldDo-Regular.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/Outfit-Bold.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/Outfit-OFL.txt",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/Outfit-Regular.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/PixelifySans-Medium.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/PixelifySans-OFL.txt",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/PoiretOne-OFL.txt",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/PoiretOne-Regular.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/RedHatMono-Bold.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/RedHatMono-OFL.txt",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/RedHatMono-Regular.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/Silkscreen-OFL.txt",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/Silkscreen-Regular.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/SmoochSans-Medium.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/SmoochSans-OFL.txt",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/Tektur-Medium.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/Tektur-OFL.txt",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/Tektur-Regular.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/WorkSans-Bold.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/WorkSans-BoldItalic.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/WorkSans-Italic.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/WorkSans-OFL.txt",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/WorkSans-Regular.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/YoungSerif-OFL.txt",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/canvas-design/canvas-fonts/YoungSerif-Regular.ttf",
        "kimi_cli/skills/canvas-design/canvas-fonts",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/LICENSE.txt",
        "kimi_cli/skills/document-skills/docx",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/SKILL.md",
        "kimi_cli/skills/document-skills/docx",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/docx-js.md",
        "kimi_cli/skills/document-skills/docx",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml.md",
        "kimi_cli/skills/document-skills/docx",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016/dml-chart.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016/dml-chartDrawing.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016/dml-diagram.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016/dml-lockedCanvas.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016/dml-main.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016/dml-picture.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016/dml-spreadsheetDrawing.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016/dml-wordprocessingDrawing.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016/pml.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016/shared-additionalCharacteristics.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016/shared-bibliography.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016/shared-commonSimpleTypes.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016/shared-customXmlDataProperties.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016/shared-customXmlSchemaProperties.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016/shared-documentPropertiesCustom.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016/shared-documentPropertiesExtended.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016/shared-documentPropertiesVariantTypes.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016/shared-math.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016/shared-relationshipReference.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016/sml.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016/vml-main.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016/vml-officeDrawing.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016/vml-presentationDrawing.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016/vml-spreadsheetDrawing.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016/vml-wordprocessingDrawing.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016/wml.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016/xml.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ecma/fouth-edition/opc-contentTypes.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ecma/fouth-edition",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ecma/fouth-edition/opc-coreProperties.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ecma/fouth-edition",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ecma/fouth-edition/opc-digSig.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ecma/fouth-edition",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/ecma/fouth-edition/opc-relationships.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/ecma/fouth-edition",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/mce/mc.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/mce",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/microsoft/wml-2010.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/microsoft",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/microsoft/wml-2012.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/microsoft",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/microsoft/wml-2018.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/microsoft",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/microsoft/wml-cex-2018.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/microsoft",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/microsoft/wml-cid-2016.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/microsoft",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/microsoft/wml-sdtdatahash-2020.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/microsoft",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/ooxml/schemas/microsoft/wml-symex-2015.xsd",
        "kimi_cli/skills/document-skills/docx/ooxml/schemas/microsoft",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/scripts/templates/comments.xml",
        "kimi_cli/skills/document-skills/docx/scripts/templates",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/scripts/templates/commentsExtended.xml",
        "kimi_cli/skills/document-skills/docx/scripts/templates",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/scripts/templates/commentsExtensible.xml",
        "kimi_cli/skills/document-skills/docx/scripts/templates",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/scripts/templates/commentsIds.xml",
        "kimi_cli/skills/document-skills/docx/scripts/templates",
    ),
    (
        "src/kimi_cli/skills/document-skills/docx/scripts/templates/people.xml",
        "kimi_cli/skills/document-skills/docx/scripts/templates",
    ),
    (
        "src/kimi_cli/skills/document-skills/pdf/LICENSE.txt",
        "kimi_cli/skills/document-skills/pdf",
    ),
    (
        "src/kimi_cli/skills/document-skills/pdf/SKILL.md",
        "kimi_cli/skills/document-skills/pdf",
    ),
    (
        "src/kimi_cli/skills/document-skills/pdf/forms.md",
        "kimi_cli/skills/document-skills/pdf",
    ),
    (
        "src/kimi_cli/skills/document-skills/pdf/reference.md",
        "kimi_cli/skills/document-skills/pdf",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/LICENSE.txt",
        "kimi_cli/skills/document-skills/pptx",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/SKILL.md",
        "kimi_cli/skills/document-skills/pptx",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/html2pptx.md",
        "kimi_cli/skills/document-skills/pptx",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml.md",
        "kimi_cli/skills/document-skills/pptx",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016/dml-chart.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016/dml-chartDrawing.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016/dml-diagram.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016/dml-lockedCanvas.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016/dml-main.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016/dml-picture.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016/dml-spreadsheetDrawing.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016/dml-wordprocessingDrawing.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016/pml.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016/shared-additionalCharacteristics.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016/shared-bibliography.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016/shared-commonSimpleTypes.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016/shared-customXmlDataProperties.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016/shared-customXmlSchemaProperties.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016/shared-documentPropertiesCustom.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016/shared-documentPropertiesExtended.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016/shared-documentPropertiesVariantTypes.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016/shared-math.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016/shared-relationshipReference.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016/sml.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016/vml-main.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016/vml-officeDrawing.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016/vml-presentationDrawing.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016/vml-spreadsheetDrawing.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016/vml-wordprocessingDrawing.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016/wml.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016/xml.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ISO-IEC29500-4_2016",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ecma/fouth-edition/opc-contentTypes.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ecma/fouth-edition",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ecma/fouth-edition/opc-coreProperties.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ecma/fouth-edition",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ecma/fouth-edition/opc-digSig.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ecma/fouth-edition",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/ecma/fouth-edition/opc-relationships.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/ecma/fouth-edition",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/mce/mc.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/mce",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/microsoft/wml-2010.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/microsoft",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/microsoft/wml-2012.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/microsoft",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/microsoft/wml-2018.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/microsoft",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/microsoft/wml-cex-2018.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/microsoft",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/microsoft/wml-cid-2016.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/microsoft",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/microsoft/wml-sdtdatahash-2020.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/microsoft",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/ooxml/schemas/microsoft/wml-symex-2015.xsd",
        "kimi_cli/skills/document-skills/pptx/ooxml/schemas/microsoft",
    ),
    (
        "src/kimi_cli/skills/document-skills/pptx/scripts/html2pptx.js",
        "kimi_cli/skills/document-skills/pptx/scripts",
    ),
    (
        "src/kimi_cli/skills/document-skills/xlsx/LICENSE.txt",
        "kimi_cli/skills/document-skills/xlsx",
    ),
    (
        "src/kimi_cli/skills/document-skills/xlsx/SKILL.md",
        "kimi_cli/skills/document-skills/xlsx",
    ),
    (
        "src/kimi_cli/skills/internal-comms/LICENSE.txt",
        "kimi_cli/skills/internal-comms",
    ),
    ("src/kimi_cli/skills/internal-comms/SKILL.md", "kimi_cli/skills/internal-comms"),
    (
        "src/kimi_cli/skills/internal-comms/examples/3p-updates.md",
        "kimi_cli/skills/internal-comms/examples",
    ),
    (
        "src/kimi_cli/skills/internal-comms/examples/company-newsletter.md",
        "kimi_cli/skills/internal-comms/examples",
    ),
    (
        "src/kimi_cli/skills/internal-comms/examples/faq-answers.md",
        "kimi_cli/skills/internal-comms/examples",
    ),
    (
        "src/kimi_cli/skills/internal-comms/examples/general-comms.md",
        "kimi_cli/skills/internal-comms/examples",
    ),
    ("src/kimi_cli/skills/kimi-cli-help/SKILL.md", "kimi_cli/skills/kimi-cli-help"),
    ("src/kimi_cli/skills/mcp-builder/LICENSE.txt", "kimi_cli/skills/mcp-builder"),
    ("src/kimi_cli/skills/mcp-builder/SKILL.md", "kimi_cli/skills/mcp-builder"),
    (
        "src/kimi_cli/skills/mcp-builder/reference/evaluation.md",
        "kimi_cli/skills/mcp-builder/reference",
    ),
    (
        "src/kimi_cli/skills/mcp-builder/reference/mcp_best_practices.md",
        "kimi_cli/skills/mcp-builder/reference",
    ),
    (
        "src/kimi_cli/skills/mcp-builder/reference/node_mcp_server.md",
        "kimi_cli/skills/mcp-builder/reference",
    ),
    (
        "src/kimi_cli/skills/mcp-builder/reference/python_mcp_server.md",
        "kimi_cli/skills/mcp-builder/reference",
    ),
    (
        "src/kimi_cli/skills/mcp-builder/scripts/example_evaluation.xml",
        "kimi_cli/skills/mcp-builder/scripts",
    ),
    (
        "src/kimi_cli/skills/mcp-builder/scripts/requirements.txt",
        "kimi_cli/skills/mcp-builder/scripts",
    ),
    ("src/kimi_cli/skills/skill-creator/LICENSE.txt", "kimi_cli/skills/skill-creator"),
    ("src/kimi_cli/skills/skill-creator/SKILL.md", "kimi_cli/skills/skill-creator"),
    (
        "src/kimi_cli/skills/slack-gif-creator/LICENSE.txt",
        "kimi_cli/skills/slack-gif-creator",
    ),
    (
        "src/kimi_cli/skills/slack-gif-creator/SKILL.md",
        "kimi_cli/skills/slack-gif-creator",
    ),
    (
        "src/kimi_cli/skills/slack-gif-creator/requirements.txt",
        "kimi_cli/skills/slack-gif-creator",
    ),
    ("src/kimi_cli/skills/template-skill/SKILL.md", "kimi_cli/skills/template-skill"),
    ("src/kimi_cli/skills/theme-factory/LICENSE.txt", "kimi_cli/skills/theme-factory"),
    ("src/kimi_cli/skills/theme-factory/SKILL.md", "kimi_cli/skills/theme-factory"),
    (
        "src/kimi_cli/skills/theme-factory/theme-showcase.pdf",
        "kimi_cli/skills/theme-factory",
    ),
    (
        "src/kimi_cli/skills/theme-factory/themes/arctic-frost.md",
        "kimi_cli/skills/theme-factory/themes",
    ),
    (
        "src/kimi_cli/skills/theme-factory/themes/botanical-garden.md",
        "kimi_cli/skills/theme-factory/themes",
    ),
    (
        "src/kimi_cli/skills/theme-factory/themes/desert-rose.md",
        "kimi_cli/skills/theme-factory/themes",
    ),
    (
        "src/kimi_cli/skills/theme-factory/themes/forest-canopy.md",
        "kimi_cli/skills/theme-factory/themes",
    ),
    (
        "src/kimi_cli/skills/theme-factory/themes/golden-hour.md",
        "kimi_cli/skills/theme-factory/themes",
    ),
    (
        "src/kimi_cli/skills/theme-factory/themes/midnight-galaxy.md",
        "kimi_cli/skills/theme-factory/themes",
    ),
    (
        "src/kimi_cli/skills/theme-factory/themes/modern-minimalist.md",
        "kimi_cli/skills/theme-factory/themes",
    ),
    (
        "src/kimi_cli/skills/theme-factory/themes/ocean-depths.md",
        "kimi_cli/skills/theme-factory/themes",
    ),
    (
        "src/kimi_cli/skills/theme-factory/themes/sunset-boulevard.md",
        "kimi_cli/skills/theme-factory/themes",
    ),
    (
        "src/kimi_cli/skills/theme-factory/themes/tech-innovation.md",
        "kimi_cli/skills/theme-factory/themes",
    ),
    (
        "src/kimi_cli/skills/webapp-testing/LICENSE.txt",
        "kimi_cli/skills/webapp-testing",
    ),
    ("src/kimi_cli/skills/webapp-testing/SKILL.md", "kimi_cli/skills/webapp-testing"),
    ("src/kimi_cli/tools/ask_user/description.md", "kimi_cli/tools/ask_user"),
    ("src/kimi_cli/tools/dmail/dmail.md", "kimi_cli/tools/dmail"),
    ("src/kimi_cli/tools/file/glob.md", "kimi_cli/tools/file"),
    ("src/kimi_cli/tools/file/grep.md", "kimi_cli/tools/file"),
    ("src/kimi_cli/tools/file/read.md", "kimi_cli/tools/file"),
    ("src/kimi_cli/tools/file/read_media.md", "kimi_cli/tools/file"),
    ("src/kimi_cli/tools/file/replace.md", "kimi_cli/tools/file"),
    ("src/kimi_cli/tools/file/write.md", "kimi_cli/tools/file"),
    ("src/kimi_cli/tools/multiagent/create.md", "kimi_cli/tools/multiagent"),
    ("src/kimi_cli/tools/multiagent/task.md", "kimi_cli/tools/multiagent"),
    ("src/kimi_cli/tools/shell/bash.md", "kimi_cli/tools/shell"),
    ("src/kimi_cli/tools/shell/powershell.md", "kimi_cli/tools/shell"),
    ("src/kimi_cli/tools/think/think.md", "kimi_cli/tools/think"),
    ("src/kimi_cli/tools/todo/set_todo_list.md", "kimi_cli/tools/todo"),
    ("src/kimi_cli/tools/web/fetch.md", "kimi_cli/tools/web"),
    ("src/kimi_cli/tools/web/search.md", "kimi_cli/tools/web"),
])


def test_pyinstaller_hiddenimports():
    from kimi_cli.utils.pyinstaller import hiddenimports

    assert sorted(hiddenimports) == snapshot(
        [
            "kimi_cli.tools",
            "kimi_cli.tools.ask_user",
            "kimi_cli.tools.display",
            "kimi_cli.tools.dmail",
            "kimi_cli.tools.file",
            "kimi_cli.tools.file.glob",
            "kimi_cli.tools.file.grep_local",
            "kimi_cli.tools.file.read",
            "kimi_cli.tools.file.read_media",
            "kimi_cli.tools.file.replace",
            "kimi_cli.tools.file.utils",
            "kimi_cli.tools.file.write",
            "kimi_cli.tools.multiagent",
            "kimi_cli.tools.multiagent.create",
            "kimi_cli.tools.multiagent.task",
            "kimi_cli.tools.shell",
            "kimi_cli.tools.test",
            "kimi_cli.tools.think",
            "kimi_cli.tools.todo",
            "kimi_cli.tools.utils",
            "kimi_cli.tools.web",
            "kimi_cli.tools.web.fetch",
            "kimi_cli.tools.web.search",
            "setproctitle",
        ]
    )
